### ISSUE TITLE
500 Internal Server Error .....

### ISSUE THREAD

**Issue by frisk0926** [unclecode/groqcall#28]
I am actually in China, i find that  when i use the requests to post     "https://groqcall.ai/proxy/groq/v1/chat/completions"  ,it works and there is no error   ,but when I deploy the program running locally according to the deployment order described by you, an internal server error occurs when I call the local port

![QQ截图20240426175417](https://github.com/unclecode/groqcall/assets/129162725/3aa721b1-c37c-4739-bc6c-976dc2c9a69a)
Which means I was intercepted by groq....

But I can access into "http://localhost:8000/proxy/groq/v1/chat/completions" from the browser, and shows the style of the json

Is there any way to fix this without mounting the clash web proxy??

Thank you for answering for me !!!!!!!

**Comment by frisk0926** [comment]
i can view the following json data through my browser
![QQ截图20240426180351](https://github.com/unclecode/groqcall/assets/129162725/dc2d6ab5-bbc3-4778-9207-ed3bd4dad879)
But it doesn't work

**Comment by unclecode** [comment]
Hey @frisk0926 , sorry to hear that. My suggestion is to set up your own "groqcall.ai" server outside China, using one of the available options to launch a Linux server. I can create a Docker image for this to make it easier. Give it a shot, and if you run into any issues, just let me know!

**Comment by frisk0926** [comment]
> Hey @frisk0926 , sorry to hear that. My suggestion is to set up your own "groqcall.ai" server outside China, using one of the available options to launch a Linux server. I can create a Docker image for this to make it easier. Give it a shot, and if you run into any issues, just let me know!

Thanks for your reply! I want to know if the address is "https://groqcall.ai/proxy/groq/v1" through the cloud function and a custom domain name to implement can replace groq API? I have used cloudflare worker and self-defined domain name to reverse proxy "api.groq.com" before, but the proxy cannot be freely invoked locally afterwards, and network proxy is still needed. May I ask whether this is due to the geographical distribution of the server to which the cloud function belongs

**Comment by unclecode** [comment]
Totally! If u find a cloud provider that vibes well with the geo location, u can totally swap it out with "api.groq.com".

**Comment by frisk0926** [comment]
I have been trying to use the serverless cloud function to complete the proxy "api.groq.com", but it has not been possible because it would cause my local IP address to be sent along with the requests, resulting in a ban. Now I understand that you are using VPS outside China to deploy fastapi to implement the operation of calling groq's API. Does this mean that in my case, all serverless cloud function operations will not work?

**Comment by unclecode** [comment]
> I have been trying to use the serverless cloud function to complete the proxy "api.groq.com", but it has not been possible because it would cause my local IP address to be sent along with the requests, resulting in a ban. Now I understand that you are using VPS outside China to deploy fastapi to implement the operation of calling groq's API. Does this mean that in my case, all serverless cloud function operations will not work?

Let's say u have a server in location A that can talk to api.groq.com and is reachable from your area. Then in A, make a fastapi app or serverless function to handle your groq request and communicate with A. Basically, act as a proxy.

**Comment by frisk0926** [comment]
Thanks for your explanation .Now I know how it works. Can you share some VPS providers or serverless cloud functions that only target API calls, except cloudflare….   I seem to find that serverless cloud functions that call groq‘s api all will be blocked…

**Comment by frisk0926** [comment]
> > I have been trying to use the serverless cloud function to complete the proxy "api.groq.com", but it has not been possible because it would cause my local IP address to be sent along with the requests, resulting in a ban. Now I understand that you are using VPS outside China to deploy fastapi to implement the operation of calling groq's API. Does this mean that in my case, all serverless cloud function operations will not work?
> 
> Let's say u have a server in location A that can talk to api.groq.com and is reachable from your area. Then in A, make a fastapi app or serverless function to handle your groq request and communicate with A. Basically, act as a proxy.

And I d like to know how long do you plan to keep the groqcall API proxy service open😂

**Comment by unclecode** [comment]
> > > I have been trying to use the serverless cloud function to complete the proxy "api.groq.com", but it has not been possible because it would cause my local IP address to be sent along with the requests, resulting in a ban. Now I understand that you are using VPS outside China to deploy fastapi to implement the operation of calling groq's API. Does this mean that in my case, all serverless cloud function operations will not work?
> > 
> > 
> > Let's say u have a server in location A that can talk to api.groq.com and is reachable from your area. Then in A, make a fastapi app or serverless function to handle your groq request and communicate with A. Basically, act as a proxy.
> 
> And I d like to know how long do you plan to keep the groqcall API proxy service open😂

😂 No worries, it'll be around for quite some time. We're actually working on a new version that focuses heavily on function calling, so enjoy using it!
